name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser furo
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Debug current directory
        run: |
          pwd
          ls -R
      - name: Build HTML documentation
        working-directory: docs
        run: |
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
